version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tp_positionnement_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tp_positionnement
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tp_network

volumes:
  db_data:

networks:
  tp_network:
